from enum import StrEnum

class TransactionType(StrEnum):
    REWARD = "REWARD"
    TRANSFER = "TRANSFER"
    SUBSCRIPTION_PAYMENT = "SUBSCRIPTION_PAYMENT"
    PURCHASE = "PURCHASE"
    PURCHASE_REFUND = "PURCHASE_REFUND"
    TRANSFER_REFUND = "TRANSFER_REFUND"
    WITHDRAWAL = "WITHDRAWAL"