"""create wallet balances table

Revision ID: 51bd6134d37d
Revises: da63492de025
Create Date: 2026-05-20 20:04:02.506448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bd6134d37d'
down_revision: Union[str, Sequence[str], None] = 'da63492de025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_balances',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_balances')
    # ### end Alembic commands ###
