"""create subscriptions table

Revision ID: 85c67f72a5cc
Revises: b6346044555b
Create Date: 2026-05-29 13:05:42.428783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c67f72a5cc'
down_revision: Union[str, Sequence[str], None] = 'b6346044555b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_actor_id', sa.UUID(), nullable=False),
    sa.Column('service_actor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['subscriber_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_next_billing_at'), 'subscriptions', ['next_billing_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_service_actor_id'), 'subscriptions', ['service_actor_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriber_actor_id'), 'subscriptions', ['subscriber_actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscriber_actor_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_service_actor_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_billing_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
