"""create transactions table

Revision ID: b527ff9d698a
Revises: d3969473dd92
Create Date: 2026-05-23 22:59:23.486079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b527ff9d698a'
down_revision: Union[str, Sequence[str], None] = 'd3969473dd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('sender_actor_id', sa.UUID(), nullable=False),
    sa.Column('receiver_actor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reference_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['sender_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_receiver_actor_id'), 'transactions', ['receiver_actor_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_transaction_id'), 'transactions', ['reference_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_actor_id'), 'transactions', ['sender_actor_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender_actor_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_actor_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
