"""empty message

Revision ID: b8372f45af77
Revises: 51bd6134d37d
Create Date: 2026-05-21 11:03:26.763816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8372f45af77'
down_revision: Union[str, Sequence[str], None] = '51bd6134d37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_actor_id'), 'ledger_entries', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_actor_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
