"""create actors table

Revision ID: da63492de025
Revises: 0ccdacbcf3bd
Create Date: 2026-05-18 21:56:04.289522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da63492de025'
down_revision: Union[str, Sequence[str], None] = '0ccdacbcf3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_index(op.f('ix_actors_actor_type'), 'actors', ['actor_type'], unique=False)
    op.create_index(op.f('ix_actors_email'), 'actors', ['email'], unique=True)
    op.create_index(op.f('ix_actors_role'), 'actors', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actors_role'), table_name='actors')
    op.drop_index(op.f('ix_actors_email'), table_name='actors')
    op.drop_index(op.f('ix_actors_actor_type'), table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
